appiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports: 
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/sqlserver/data
            name: sqlserverdb
      volumes:
      - name: sqlserver
        persistentVolumeClaim:
          claimName: sqlserver-claim
---
apiVersion: v1
kind: Service
metadata: 
  name: sqlserver-clusterip-srv
spec: 
  type: ClusterIP
  selector: 
    app: sqlserver
  ports:
  - name: sqlserver
    protocol: TCP
    port: 1433
    targetPort: 1433 
---
apiVersion: v1
kind: Service
metadata: 
  name: sqlserver-loadbalancer
spec: 
  type: LoadBalancer
  selector: 
    app: sqlserver
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433